FROM docker.io/rustembedded/cross:x86_64-pc-windows-gnu

RUN dpkg --add-architecture i386 && apt-get update && \
    apt-get install --assume-yes --no-install-recommends \
    llvm-dev \
    libclang-dev \
    clang
