FROM rustembedded/cross:x86_64-pc-windows-gnu

RUN dpkg --add-architecture i386 && apt-get update && \
    apt-get install --assume-yes --no-install-recommends \
    wine-stable \
    wine64 \
    wine32 \
    libz-mingw-w64-dev \
    llvm-dev \
    libclang-dev \
    clang
